fix: make multiprocessing work on OSX.
By default, OS X multiprocessing starts processes with spawn() instead of
fork(). When spawning, data is sent by pickling which leads to TypeErrors:

> TypeError: cannot pickle '_thread.lock' object

The workaround is simply to run multiprocessing.set_start_method("fork")