fix(extractor): fix report typing issue with ExtractCommandFailedReport
The ExtractCommandFailedReport class only accepts bytes for its stdout
and stderr fields.

The subprocess.run call that executes the extraction command returns a
subprocess.CompletedProcess object, where its stdout and stderr can be
either bytes, str, or None depending on how it was called (see
https://docs.python.org/3/library/subprocess.html#subprocess.CompletedProcess).

This discrepancy triggered pydantic validation error since, especially
in the gzip handler:

File
"/nix/store/zgivnxh4vs6cwappddrmqfmbxx8f3l7m-inspector-env/lib/python3.13/site-packages/unblob/handlers/compression/gzip.py",
line 92, in extract
    return extractor.extract(inpath, outdir)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File
"/nix/store/zgivnxh4vs6cwappddrmqfmbxx8f3l7m-inspector-env/lib/python3.13/site-packages/unblob/extractors/command.py",
line 60, in extract
    error_report = ExtractCommandFailedReport(
        command=command,
    ...&lt;2 lines&gt;...
        exit_code=res.returncode,
    )
  File
"/nix/store/zgivnxh4vs6cwappddrmqfmbxx8f3l7m-inspector-env/lib/python3.13/site-packages/pydantic/main.py",
line 250, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data,
self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for
ExtractCommandFailedReport
stdout
  Input should be a valid bytes [type=bytes_type, input_value=None,
input_type=NoneType]
    For further information visit
https://errors.pydantic.dev/2.12/v/bytes_type

We now normalize these fields to bytes to make sure the model is
strictly followed.

This is unrelated to 3513bcc since pydantic models of unblob reports
were already validated prior.