flake.nix: adding missing declaration for `shell.nix`
`shell.nix` was changed recently to use the package set from
`flake.nix`, however the required output attribute was missing,
causing this error:

```
error: attribute 'legacyPackages' missing

       at /home/vlaci/devel/git/github.com/IoT-Inspector/unblob/shell.nix:4:15:

            3|   flake = builtins.getFlake (toString ./.);
            4|   flakePkgs = flake.legacyPackages.${builtins.currentSystem};
             |               ^
            5| in
```