rust: increase MSRV to 1.60.0 due to requirements of test dependencies
> error: package `csv v1.2.0` cannot be built because it requires
> rustc 1.60 or newer, while the currently active rustc version is
> 1.57.0