fix(pre-commit): work-around false-positive lint error on Rust 1.84+
It shows

    error: unexpected `cfg` condition value: `gil-refs`

during clippy execution

The error is due to a new lint turned on on Rust 1.84 which trips
older PyO3 code. It'll go away when upgrading to 0.23[^1], but it needs
API changes, so for the time being the lint is disabled instead.

[^1]: https://github.com/PyO3/pyo3/issues/4743